# Generated by Django 5.2.5 on 2025-08-14 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_description_product_price_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.unitofmeasure'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku_base',
            field=models.SlugField(blank=True, help_text='Base/parent SKU', max_length=60, null=True),
        ),
    ]
